tokens={
    "verification": "verification",
    "invalid": "verification",
    "validate": "verification",
    "task": "handle exception error",
    "opcomplete":"handle exception error",
    "job error":"handle exception error",
    "error occurred": "handle exception error",
    "unexpected error":"handle exception error",
    "exception": "handle exception error",
    "method": "handle exception error",
    "ошибка": "handle exception error",
    "execution": "handle exception error",
    "unable": "handle exception error",
    "unhandled": "handle exception error",
    "request": "database",
    "query": "database",
    "get": "database",
    "delete": "database",
    "from": "database",
    "select": "database",
    "where": "database",
    "connection": "database",
    "database": "database",
    "nhibernate": "database",
    "documents": "database",
    "file storage": "database",
    "disk": "database",
    "file": "database",
    "data": "database",
    "данные": "database",
    "пакет": "database",
    "загрузка": "database",
    "загрузился": "database",
    "Timeout": "timeout",
    "time out": "timeout",
    "denied":"access",
    "не разрешено": "access",
    "already": "obj already added",
    "rabbitmq": "broker",
    "pp3": "broker",
    "not found": "not found",
    "не найдено": "not found",
    "не найден": "not found",
    "не найдена": "not found",
    "не удалось считать": "not found",
    "капча": "captcha",
    "капчи": "captcha",
    "capha": "captcha",
    "import": "import",
    "реиндексация":"database",
    "подписание по старому сертификату":"obsolete data",
    "не удалось скачать":"not found",
    "timed out":"timeout"
}